# Generated by Django 6.0.1 on 2026-01-30 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход'), ('transfer', 'Перевод')], default='expense', max_length=10),
        ),
    ]
