# Generated by Django 5.1.2 on 2026-02-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_category_options_remove_category_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='members_can_create_goals',
            field=models.BooleanField(default=True, verbose_name='Участники могут создавать цели'),
        ),
        migrations.AddField(
            model_name='family',
            name='members_can_invite',
            field=models.BooleanField(default=False, verbose_name='Участники могут приглашать'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='display_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Отображаемое имя в семье'),
        ),
    ]
