# Generated by Django 5.0.7 on 2026-02-04 11:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_family_settings_and_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialgoal',
            name='last_replenishment_at',
            field=models.DateField(blank=True, null=True, verbose_name='Последнее пополнение'),
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='replenishment_frequency',
            field=models.CharField(blank=True, choices=[('', 'Без обязательного графика'), ('daily', 'Раз в день'), ('every_2_days', 'Раз в 2 дня'), ('every_3_days', 'Раз в 3 дня'), ('weekly', 'Раз в неделю'), ('monthly', 'Раз в месяц')], default='', max_length=20, verbose_name='Пополнение'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('budget_warning', 'Превышение бюджета'), ('bill_reminder', 'Напоминание о счете'), ('goal_progress', 'Прогресс цели'), ('goal_replenishment_reminder', 'Напоминание о пополнении цели'), ('family_invite', 'Приглашение в семью'), ('member_joined', 'Участник присоединился к семье'), ('transaction_added', 'Добавлена транзакция'), ('system', 'Системное уведомление')], max_length=30),
        ),
        migrations.CreateModel(
            name='GoalContribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('contributed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='finance.financialgoal')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goal_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пополнение цели',
                'verbose_name_plural': 'Пополнения целей',
                'ordering': ['-contributed_at'],
            },
        ),
    ]
