# Generated by Django 5.1.2 on 2026-02-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_goal_replenishment_and_contributions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='block_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина блокировки'),
        ),
    ]
