# Generated by Django 5.1.2 on 2026-02-07 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_add_block_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecast',
            name='user',
        ),
        migrations.RemoveField(
            model_name='importtemplate',
            name='default_account',
        ),
        migrations.RemoveField(
            model_name='importtemplate',
            name='default_category',
        ),
        migrations.RemoveField(
            model_name='importtemplate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mlmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='report',
            name='family',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CategorizationRule',
        ),
        migrations.DeleteModel(
            name='Forecast',
        ),
        migrations.DeleteModel(
            name='ImportTemplate',
        ),
        migrations.DeleteModel(
            name='MLModel',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
